#!/bin/bash
export JAVA_TOOL_OPTIONS="-Xmx128m"
#opt -print-callgraph $1  2>graphoutput.txt 1>/dev/null
opt -print-callgraph $1 2>&1 >/dev/null  | java -cp ../  PiPair $@
#java -cp ../ -Xms128m  PiPair graphoutput.txt $2 $3

